controller_list:
  - name: fake_arm_controller
    joints:
      - base_link__link_04
      - link_04__link_05
      - link_05__link_06
      - link_06__link_07
      - link_07__link_08
      - link_08__link_09